#Definir todos los contenedores
#Un contenedor puede etsar en varios puertos
# Definir todos los contenedores
services:
  #Contenedor de la API
  #http://localhost:3005/
  api:
    build:
      context: .
    ports:
      - 3005:3000
  db:
    image: mysql:8
    container_name: MySQLDockerCompose
    # Un contenedor puede estar en varios puertos, pero no puede mapear el mismo puerto interno a más de uno externo
    ports: 
      - 3415:3306
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
    volumes:
      - db_mysql:/var/lib/mysql
#Kubbernetes
  box3:
    image: alpine
    #container_name: Box3
    command: sleep 3600
    deploy:
      replicas: 8

  box4:
    image: alpine
    container_name: Box4
    command: sleep 3600
    
volumes:
  db_mysql:


#Levantar con
# docker compose up -d

#Tumbar
# docker compose down

#Levantar API