name: Docker Build & Publish
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone My Repository
        uses: actions/checkout@v2
        #Ir al repositorio de git, settigns, secrets, add 
      - name: Login to Docker Hub o cualquie 
        run: docker login -u "${{secrets.DOCKER_USERNAME}}" -p "${{secrets.DOCKER_PASSWORD}}"

      - name: Construir imagen con commit
        run: docker build -t fernandaballesteros/docker-fundamentals:${{ github.sha }} .
      #Crear copia de imagen pero con tag
      - name: Renonmbrar imagen con commit
        run: docker tag fernandaballesteros/docker-fundamentals:${{ github.sha }} fernandaballesteros/docker-fundamentals:latest

      - name: Publicar imagen
        run: |
          docker push fernandaballesteros/docker-fundamentals:${{ github.sha }} 
          docker push fernandaballesteros/docker-fundamentals:latest